#:set color1_ever (0.45, 0.37, 0.24, 1.0) #background 
#:set color2_ever (0.2196078431372549, 0.4, 0.2549019607843137, 1.0)  #Labels
#:set color3_ever (1.0, 0.9019607843137255, 0.6549019607843137, 1.0)  #Font

#:set color1_pagan (0.4235294117647059, 0.4588235294117647, 0.49019607843137253, 1.0) #background
#:set color2_pagan (0.32941176470588235, 0.043137254901960784, 0.054901960784313725, 0.8) #Labels
#:set color3_pagan (1.0, 0.9529411764705882, 0.6901960784313725, 1.0) #Font

#:set color1_wonders (0.12941176470588237, 0.6196078431372549, 0.7372549019607844, 1.0) #background
#:set color2_wonders (0.0, 0.20784313725490197, 0.4, 1.0) #Labels
#:set color3_wonders (1.0, 0.8392156862745098, 0.0392156862745098, 1.0) #Font

#:set color1_neutral (0.6784313725490196, 0.7098039215686275, 0.7411764705882353, 1.0) #background
#:set color2_neutral (0.01568627450980392, 0.2784313725490196, 0.10980392156862745, 1.0) #Labels
#:set color3_neutral (0.8117647058823529, 0.8784313725490196, 0.7647058823529411, 1.0) #Font



ScreenManager:

    MainScreen:
    EverScreen:
    PaganScreen:
    WondersScreen:
    CleverScreen:
    Clever4Screen:
    KniffelScreen:
    TargiScreen:
    DiceScreen:
    HarmoniesScreen:


<ScoreLabel@Label>:
    font_size: "64sp"
    bold: True
    halign: "center"
    valign: "middle"
    text_size: self.size
    padding: dp(8), dp(8)
    canvas.before:
        Color:
            rgba: 0.08, 0.12, 0.20, 0.96
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(18), dp(18), dp(18), dp(18)]

<StreakLabel@Label>:
    font_size: "16sp"
    size_hint: 0.25, 0.05
    background_normal: ""
    background_down: ""
    background_color: 0, 0, 0, 0
    color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: 0.08, 0.12, 0.20, 0.96
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(18), dp(18), dp(18), dp(18)]
<LastWinLabel@Label>:
    font_size: "12sp"
    size_hint: 0.4, 0.05
    background_normal: ""
    background_down: ""
    background_color: 0, 0, 0, 0
    color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: 0.08, 0.12, 0.20, 0.96
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(18), dp(18), dp(18), dp(18)]
<PlusButton@Button>:
    text: "+"
    font_size: "30sp"
    size_hint: 0.1, 0.05
    background_normal: ""
    background_down: ""
    background_color: 0, 0, 0, 0
    color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: 0.08, 0.12, 0.20, 0.96
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(18), dp(18), dp(18), dp(18)]
    
<MinusButton@Button>:
    text: "-"
    font_size: "30sp"
    size_hint: 0.1, 0.05
    background_normal: ""
    background_down: ""
    background_color: 0, 0, 0, 0
    color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: 0.08, 0.12, 0.20, 0.96
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(18), dp(18), dp(18), dp(18)]

<MainScreen@Screen>:
    name: "main"
    
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0.7450980392156863, 0.5843137254901961, 0.7686274509803922, 1.0                                          #0.2901960784313726, 0.2901960784313726, 0.2901960784313726, 1.0
            Rectangle:
                pos: self.pos
                size: self.size

        GridLayout:
            cols: 3
            spacing: 5
            padding: 5
            
            ImageButton:
                source: "Images_fixed/everdell2.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Ever")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/pagan.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Pagan")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/sevenwonders.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Wonders")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/Clever.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Ganz schön Clever")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/Clever4.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Clever 4 ever")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/Kniffel.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Kniffel")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/Targi.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Targi")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/Dice.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Dice Throne")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            ImageButton:
                source: "Images_fixed/Harmonies.png"
                allow_stretch: True
                keep_ratio: False
                on_press: app.image_clicked("Harmonies")
                canvas.before:
                    Color:
                        rgba: 0.10, 0.10, 0.14, 1   # background color of each tile
                    Rectangle:
                        pos: self.pos
                        size: self.size

            Button:
                text: "Create Profile"
                on_press: app.show_input()
            Button:
                text: "Load Profile"
                on_press: app.show_profiles(mode="load")
            Button:
                text: "Delete Profile"
                on_press: app.show_profiles(mode="delete")
            Button:
                text: "Share Profile"
                on_press: app.share_current_profile()
            Button:
                text: "Join Shared"
                on_press: app.show_join()
            Button:
                text: "Sync Now"
                on_press: app.sync_now()
<EverScreen@Screen>:
    name: "Ever"

    FloatLayout: 
        canvas.before:
            Color:
                rgba: color1_ever
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Everdell: " + app.current_profile
            font_size: "32sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_ever
            pos_hint: {"center_x":0.5,"top":1}
            size_hint: 1, 0.3
            text_size: self.size
            halign: "center"
            valign: "middle"
            canvas.before:
                Color:
                    rgba: color2_ever
                Rectangle:
                    pos: self.pos
                    size: self.size

        ScoreLabel:
            text: str(app.scores["Ever"][0][0])
            color: 0.25, 0.65, 1, 1
            pos_hint: {"center_x":0.255,"top":0.67}
            size_hint: 0.3, 0.2
        ScoreLabel:
            text: str(app.scores["Ever"][0][1])
            color: 1, 0.55, 0.2, 1
            pos_hint: {"center_x":0.745,"top":0.67}
            size_hint: 0.3, 0.2
        LastWinLabel: 
            text: "Last Win: " + app.scores["Ever"][1][0]
            pos_hint: {"center_x":0.255,"top":0.3}
        LastWinLabel: 
            text: "Last Win: " + app.scores["Ever"][1][1]
            pos_hint: {"center_x":0.745,"top":0.3}
        StreakLabel: 
            text: "Streak: " + str(app.scores["Ever"][2][0])
            pos_hint: {"center_x":0.255,"top":0.375}
        StreakLabel: 
            text: "Streak: " + str(app.scores["Ever"][2][1])
            pos_hint: {"center_x":0.745,"top":0.375}

        Button:
            text: "Back"
            font_size: "48sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_ever
            background_normal: ""
            background_down: ""
            background_color: color2_ever
            on_press: app.root.current = "main"
            pos_hint: {"center_x":0.5,"top":0.2}
            size_hint: 0.4, 0.1
        PlusButton:
            on_press: app.change_score("Ever",0,1)
            pos_hint: {"center_x":0.17,"top":0.45}
        MinusButton:
            on_press: app.change_score("Ever",0,-1)
            pos_hint: {"center_x":0.34,"top":0.45}

        PlusButton:
            on_press: app.change_score("Ever",1,1)
            pos_hint: {"center_x":0.66,"top":0.45}
        MinusButton:
            on_press: app.change_score("Ever",1,-1)
            pos_hint: {"center_x":0.83,"top":0.45}
            


<PaganScreen@Screen>:
    name: "Pagan"

    FloatLayout:
        canvas.before:
            Color:
                rgba: color1_pagan
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Pagan: " + app.current_profile
            font_size: "32sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_pagan
            pos_hint: {"center_x":0.5,"top":1}
            size_hint: 1, 0.3
            text_size: self.size
            halign: "center"
            valign: "middle"
            canvas.before:
                Color:
                    rgba: color2_pagan
                Rectangle:
                    pos: self.pos
                    size: self.size

        ScoreLabel:
            text: str(app.scores["Pagan"][0][0])
            color: 0.25, 0.65, 1, 1
            pos_hint: {"center_x":0.255,"top":0.67}
            size_hint: 0.3, 0.2
        ScoreLabel:
            text: str(app.scores["Pagan"][0][1])
            color: 1, 0.55, 0.2, 1
            pos_hint: {"center_x":0.745,"top":0.67}
            size_hint: 0.3, 0.2
        LastWinLabel:
            text: "Last Win: " + app.scores["Pagan"][1][0]
            pos_hint: {"center_x":0.255,"top":0.3}
        LastWinLabel:
            text: "Last Win: " + app.scores["Pagan"][1][1]
            pos_hint: {"center_x":0.745,"top":0.3}
        StreakLabel:
            text: "Streak: " + str(app.scores["Pagan"][2][0])
            pos_hint: {"center_x":0.255,"top":0.375}
        StreakLabel:
            text: "Streak: " + str(app.scores["Pagan"][2][1])
            pos_hint: {"center_x":0.745,"top":0.375}
        Button:
            text: "Back"
            font_size: "48sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_pagan
            background_normal: ""
            background_down: ""
            background_color: color2_pagan
            on_press: app.root.current = "main"
            pos_hint: {"center_x":0.5,"top":0.2}
            size_hint: 0.4, 0.1
        PlusButton:
            on_press: app.change_score("Pagan",0,1)
            pos_hint: {"center_x":0.17,"top":0.45}
        MinusButton:
            on_press: app.change_score("Pagan",0,-1)
            pos_hint: {"center_x":0.34,"top":0.45}
        PlusButton:
            on_press: app.change_score("Pagan",1,1)
            pos_hint: {"center_x":0.66,"top":0.45}
        MinusButton:
            on_press: app.change_score("Pagan",1,-1)
            pos_hint: {"center_x":0.83,"top":0.45}
        

<WondersScreen@Screen>
    name: "Wonders"

    FloatLayout:
        canvas.before:
            Color:
                rgba: color1_wonders
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Seven Wonders: " + app.current_profile
            font_size: "32sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_wonders
            pos_hint: {"center_x":0.5,"top":1}
            size_hint: 1, 0.3
            text_size: self.size
            halign: "center"
            valign: "middle"
            canvas.before:
                Color:
                    rgba: color2_wonders
                Rectangle:
                    pos: self.pos
                    size: self.size
       
        ScoreLabel:
            text: str(app.scores["Wonders"][0][0])
            color: 0.25, 0.65, 1, 1
            pos_hint: {"center_x":0.255,"top":0.67}
            size_hint: 0.3, 0.2
        ScoreLabel:
            text: str(app.scores["Wonders"][0][1])
            color: 1, 0.55, 0.2, 1
            pos_hint: {"center_x":0.745,"top":0.67}
            size_hint: 0.3, 0.2
        LastWinLabel:
            text: "Last Win: " + app.scores["Wonders"][1][0]
            pos_hint: {"center_x":0.255,"top":0.3}
        LastWinLabel:
            text: "Last Win: " + app.scores["Wonders"][1][1]
            pos_hint: {"center_x":0.745,"top":0.3}
        StreakLabel:
            text: "Streak: " + str(app.scores["Wonders"][2][0])
            pos_hint: {"center_x":0.255,"top":0.375}
        StreakLabel:
            text: "Streak: " + str(app.scores["Wonders"][2][1])
            pos_hint: {"center_x":0.745,"top":0.375}
        Button:
            text: "Back"
            font_size: "48sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_wonders
            background_normal: ""
            background_down: ""
            background_color: color2_wonders
            on_press: app.root.current = "main"
            pos_hint: {"center_x":0.5,"top":0.2}
            size_hint: 0.4, 0.1
        PlusButton:
            on_press: app.change_score("Wonders",0,1)
            pos_hint: {"center_x":0.17,"top":0.45}
        MinusButton:
            on_press: app.change_score("Wonders",0,-1)
            pos_hint: {"center_x":0.34,"top":0.45}
        PlusButton:
            on_press: app.change_score("Wonders",1,1)
            pos_hint: {"center_x":0.66,"top":0.45}
        MinusButton:
            on_press: app.change_score("Wonders",1,-1)
            pos_hint: {"center_x":0.83,"top":0.45}


<CleverScreen@Screen>:
    name: "Ganz schön Clever"
    subname: "Clever"

    FloatLayout:
        canvas.before:
            Color:
                rgba: color1_neutral
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: root.name + ": " + app.current_profile
            font_size: "32sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_neutral
            pos_hint: {"center_x":0.5,"top":1}
            size_hint: 1, 0.3
            text_size: self.size
            halign: "center"
            valign: "middle"
            canvas.before:
                Color:
                    rgba: color2_neutral
                Rectangle:
                    pos: self.pos
                    size: self.size

        ScoreLabel:
            text: str(app.scores[root.subname][0][0])
            color: 0.25, 0.65, 1, 1
            pos_hint: {"center_x":0.255,"top":0.67}
            size_hint: 0.3, 0.2
        ScoreLabel:
            text: str(app.scores[root.subname][0][1])
            color: 1, 0.55, 0.2, 1
            pos_hint: {"center_x":0.745,"top":0.67}
            size_hint: 0.3, 0.2
        LastWinLabel:
            text: "Last Win: " + app.scores[root.subname][1][0]
            pos_hint: {"center_x":0.255,"top":0.3}
        LastWinLabel:
            text: "Last Win: " + app.scores[root.subname][1][1]
            pos_hint: {"center_x":0.745,"top":0.3}
        StreakLabel:
            text: "Streak: " + str(app.scores[root.subname][2][0])
            pos_hint: {"center_x":0.255,"top":0.375}
        StreakLabel:
            text: "Streak: " + str(app.scores[root.subname][2][1])
            pos_hint: {"center_x":0.745,"top":0.375}
        Button:
            text: "Back"
            font_size: "48sp"
            font_name: "fonts/Medieval.ttf"
            color: color3_neutral
            background_normal: ""
            background_down: ""
            background_color: color2_neutral
            on_press: app.root.current = "main"
            pos_hint: {"center_x":0.5,"top":0.2}
            size_hint: 0.4, 0.1
        PlusButton:
            on_press: app.change_score(root.subname,0,1)
            pos_hint: {"center_x":0.17,"top":0.45}
        MinusButton:
            on_press: app.change_score(root.subname,0,-1)
            pos_hint: {"center_x":0.34,"top":0.45}
        PlusButton:
            on_press: app.change_score(root.subname,1,1)
            pos_hint: {"center_x":0.66,"top":0.45}
        MinusButton:
            on_press: app.change_score(root.subname,1,-1)
            pos_hint: {"center_x":0.83,"top":0.45}


<Clever4Screen@CleverScreen>:
    name: "Clever 4 ever"
    subname: "Clever4"

<KniffelScreen@CleverScreen>:
    name: "Kniffel"
    subname: "Kniffel"


<TargiScreen@CleverScreen>:
    name: "Targi"
    subname: "Targi"


<DiceScreen@CleverScreen>:
    name: "Dice Throne"
    subname: "Dice"

<HarmoniesScreen@CleverScreen>:
    name: "Harmonies"
    subname: "Harmonies"